version: '3.9'

services:
    api-dev:
        container_name: nestjs_api
        image: nestjs_api
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        ports:
            - 3000:3000
        networks:
            - backend
        volumes:
            - ./:/app
            - ./node_modules/:/app/node_modules
        restart: unless-stopped
        depends_on:
            - redis
            - postgres
    redis:
      image: redis
      ports:
        - 6379:6379

    postgres:
      image: postgres
      restart: always
      environment:
      POSTGRES_DB: google_oauth2_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      ports:
        - '5432:5432'
         