version: '3.9'

services:
    api-dev:
        container_name: nestjs_api
        image: nestjs_api
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
        restart: unless-stopped
        depends_on:
            - redis
            - postgres
        networks:
            - backend
        env_file:
            - .env
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379:6379
        restart: always
        env_file:
            - .env

    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always
        ports:
            - '5432:5432'
        env_file:
            - .env
networks:
    backend:
        driver: bridge
