version: "3.8"
services:
  app:
    env_file:
      - .env.example
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_USERNAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispw
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
        - 5432:5432
  redis:
    image: redis:6
    restart: always
    command: redis-server --requirepass redispw  
    ports:
        - 6379:6379 
